### ISSUE TITLE
specify cut-off by precentage

### ISSUE THREAD

**Issue by jondot** [jondot/nchurn#2]
nchurn -c 30% will only show top 30 percent of all results, regardless of churn level.

**Comment by orangy** [comment]
I didn't mean 30% of all results. I mean that number of results, so that sum of them is 30% of total. E.g.
a.cs 10
b.cs 9
c.cs 9
d.cs 7
e.cs 2
f.cs 2
g.cs 2
h.cs 2

Total is 43, for 30% we need total of ~13, which means just a and b.
For 50% we need total of 22, which means a,b,c
I.e. 50% of all changes happen in files a,b,c

**Comment by jondot** [comment]
Got it!.

**Comment by jondot** [comment]
implemented in 0.4

specify a float such as 0.4 to represent 40%.

you can use the same -c selector
NChurn -c 0.5

Hope it helps!
